# Generated by Django 4.2.4 on 2023-10-08 04:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200, unique=True)),
                ('promoting_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('status', models.BooleanField(default=1)),
                ('promoting_status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Info',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1000)),
                ('referral_id', models.CharField(max_length=8)),
                ('address', models.CharField(default=None, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ordernumber', models.IntegerField(primary_key=True, serialize=False)),
                ('if_reffered', models.BooleanField(default=0)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('purchased_email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ecomapp.login_info')),
            ],
        ),
        migrations.CreateModel(
            name='RefferedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=8)),
                ('promoting_percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('ordernumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.BooleanField(default=1)),
                ('in_stock', models.BooleanField(default=1)),
                ('promoting_link', models.CharField(max_length=700, unique=True)),
                ('promoting_status', models.BooleanField(default=1)),
                ('pimage', models.ImageField(upload_to='image')),
                ('category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='DetailComission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comission_amt', models.FloatField()),
                ('ordernumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
