# Generated by Django 4.2.4 on 2023-10-08 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='refferedorders',
            name='promoting_percent',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='refferedorders',
            name='comission_amt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetailComission',
        ),
        migrations.AddField(
            model_name='detailorder',
            name='ordernumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.orders'),
        ),
    ]
