# Generated by Django 4.2.4 on 2023-10-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_detailorder_remove_refferedorders_promoting_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferedorders',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
